<?php

namespace App\Enums;

interface ParcelStatus
{
    const PENDING                           = 1;
    const PICKUP_ASSIGN                     = 2;
    const PICKUP_RE_SCHEDULE                = 3;
    const RECEIVED_BY_PICKUP_MAN            = 4;
    const RECEIVED_WAREHOUSE                = 5;
    const TRANSFER_TO_HUB                   = 6;
    const DELIVERY_MAN_ASSIGN               = 7;
    const DELIVERY_RE_SCHEDULE              = 8;
    const DELIVERED                         = 9;
    const DELIVER                           = 10;
    const RETURN_WAREHOUSE                  = 11;
    const ASSIGN_MERCHANT                   = 12;
    const RETURNED_MERCHANT                 = 13;
    const PICKUP_ASSIGN_CANCEL              = 14;
    const RECEIVED_BY_PICKUP_MAN_CANCEL     = 15;
    const RECEIVED_WAREHOUSE_CANCEL         = 16;
    const DELIVERY_MAN_ASSIGN_CANCEL        = 17;
    const DELIVERY_RE_SCHEDULE_CANCEL       = 18;
    const RECEIVED_BY_HUB                   = 19;
    const TRANSFER_TO_HUB_CANCEL            = 20;
    const RECEIVED_BY_HUB_CANCEL            = 21;
    const DELIVERED_CANCEL                  = 22;
    const PICKUP_RE_SCHEDULE_CANCEL         = 23;
    const RETURN_TO_COURIER                 = 24;
    const RETURN_TO_COURIER_CANCEL          = 25;
    const RETURN_ASSIGN_TO_MERCHANT         = 26;
    const RETURN_MERCHANT_RE_SCHEDULE       = 27;
    const RETURN_MERCHANT_RE_SCHEDULE_CANCEL = 28;
    const RETURN_ASSIGN_TO_MERCHANT_CANCEL  = 29;
    const RETURN_RECEIVED_BY_MERCHANT       = 30;
    const RETURN_RECEIVED_BY_MERCHANT_CANCEL = 31;
    const PARTIAL_DELIVERED                 = 32;
    const PARTIAL_DELIVERED_CANCEL          = 33;
    const PARCEL_CANCEL                     = 34;

    const UNCONFIRMED                       = 35;
    const CONFIRMED                         = 36;
    const HEADING_TO_PICKUP_POINT           = 37;
    const PICKED_UP                         = 38;
    const HEADING_TO_DROP_OFF_HUB           = 39;
    const HEADING_TO_DELIVERY_POINT         = 40;
    const DROPPED_OFF_AT_HUB                = 41;
    const IMMEDIATE_EXECUTION               = 42;
    const DROP_OFf_HUB1                     = 43;
    const TRANSIT_OUT_CITY                  = 44;
    const ON_THE_WAY_TO_CITY                = 45;
    const ARRIVED_AT_CITY                   = 46;
    const DROP_OFF_CITY                     = 47;
    const SCHEDULED_EXECUTION               = 48;
    const BOOKING                           = 49;
    const READY_TO_REASSIGN_REGULAR         = 51;
    const READY_TO_REASSIGN_BOOKING         = 52;
    const CONFIRMED_BOOKING                 = 53;
    const UNCONFIRMED_BOOKING               = 54;
    const PROCESSING                        = 55;
    const DELIVERY_FAILURE                  = 56;
    const DELIVERY_FAILED                   = 57;
    const HEADING_TO_DROP_OFF               = 58;
    const DROPPED_OFF_HUB2                  = 59;
    const DELIVERY_MAN_ASSIGN_SECOND_PROVINCE       = 60;
    const DELIVERY_ATTEMPT1                         = 61;
    const DELIVERY_ATTEMPT2                         = 62;
    const DELIVERY_ATTEMPT3                         = 63;
    const DELIVERY_MAN_ASSIGN1                      = 64;
    const RETURN_ASSIGN_TO_MERCHANT1                = 65;
    const RETURN_ASSIGN_TO_MERCHANT1_CANCEL         = 66;
    const RETURNING                                 = 67;
    const TRANSIT_SENDING_PROVINCE                  = 68;
    const ON_THE_WAY_SENDING_PROVINCE               = 69;
    const ARRIVED_TO_SENDING_HUB                    = 70;
    const MARKETPLACE_PENDING                       = 71;
    const MARKETPLACE_ACCEPTED                      = 72;
    const MARKETPLACE_PICKED_UP                     = 73;
    const MARKETPLACE_DELIVERED                     = 74;
    const MARKETPLACE_CANCELLED                     = 75;
    const MARKETPLACE_SENDER_PAYMENT_AWAITING       = 76;
    const MARKETPLACE_RECEIVER_PAYMENT_AWAITING     = 77;
}
